apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  labels:
    auto-resize: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
